---
title: "Assignment 4"
author: "Kort Alexander and Grace Bianchi"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sensitivity)
library(lhs)
```

```{r}
# source conductance function
source(here("R", "Catm.R"))

# set parameters
pnames <- c("height", "k_d", "k_o", "v")
npar <- length(pnames)
nsample <- 100

# Use the Latin hypercube approach to generate parameter values for the 4 parameters
parm_quant <- randomLHS(nsample, npar)
colnames(parm_quant) <- pnames

parm = as.data.frame(matrix(nrow=nrow(parm_quant), ncol=ncol(parm_quant)))
colnames(parm) = pnames

percent_k_d_0 <- 0.01
parm[,"height"] = qunif(parm_quant[,"height"], min = 9.5, max = 10.5)
parm[,"k_d"] = qnorm(parm_quant[, "k_d"], mean = 0.7, sd = 0.7 * percent_k_d_0)
parm[,"k_o"] = qnorm(parm_quant[, "k_o"], mean = 0.1, sd = 0.1 * percent_k_d_0)
parm[, "v"] = qnorm(parm_quant[, "v"], mean = 250, sd = 30)
```

```{r}
# run our model for all of the parameters generated by LHS
results = pmap(.l=parm, .f=Catm)
# convert list to df and add Ca values into rows
results_df <- as.data.frame(do.call(rbind, results)) %>% 
  rename(conductance = V1) %>% 
  cbind(parm) # add parameter values

# tidy version for graphing
results_long <- results_df %>%  
  gather(v, height, k_o, k_d, key = "parameter", value = "value")

# labels for facet wrap
parm_labs <- c("height", "plane displacement", "roughness", "windspeed")
names(parm_labs)  <- c("height", "k_d", "k_o", "v")

# Plot conductance estimates in a way that accounts for parameter uncertainty
ggplot(results_long, aes(y = conductance, x=value, fill = parameter))+
  geom_boxplot()+
  labs(x="Atmospheric Conductance", y = "Parameter value") +
  facet_wrap(~parameter, scales="free",ncol=4, labeller = labeller(parameter = parm_labs)) +
  scale_fill_discrete(name = "parameter", labels = c("height", "zero plane displacement", "roughness", "windspeed")) +
  theme(legend.position = "none", 
        axis.text.x=element_blank(),
      axis.ticks.x=element_blank())
```

Figure 1. Boxplot of model sensitivity for parameter variations. uncertainty on atmospheric conductance. Vegetation height (height) has the greatest uncertainty and therefore biggest effect on atmoshpheric conductance.


```{r}
# Plot conductance estimates against each of your parameters


# Estimate the Partial Rank Correlation Coefficients
```

