---
title: "Assignment 7"
author: "Kort Alexander and Alia Ajina"
date: "2023-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(deSolve)
library(ggpubr)
```

```{r}
source(here("R", "lotv_w_hunting.R"))

# test function without hunting

# initial conditions
currpop = c(prey=100, pred=10)

# time points to see results
days = seq(from=1, to=100, by=1)

# set parameters
pars = c(rprey=0.95, alpha=0.01, eff=0.6,pmort=0.4, K=2000, hunted=0, min_pop = 0.5)

# run the model
res = ode(func=lotv_w_hunting, y=currpop, times=days, parms=pars)

# visualize results
resl = as.data.frame(res) %>% pivot_longer(-time, names_to="animal", values_to="pop")
p1=ggplot(resl, aes(time, pop, col=animal))+geom_line()
p1
```

```{r}
lotv_wrapper = function(currpop, days, rprey, alpha, eff, pmort, K, hunted, min_pop) {
  parms = list(rprey=rprey, alpha=alpha, eff=eff, pmort=pmort, K=K, hunted=hunted, min_pop=min_pop)
  result = ode(y=currpop, times=days, func=lotv_w_hunting, parms=parms) 
  colnames(result)=c("time","prey","pred")
  return(result)
}

# run function with hunting
pars = list(rprey=0.95, alpha=0.01, eff=0.6,pmort=0.4, K=2000, hunted = seq(from=100, to=300, by=10), min_pop = 460)
all_res = as.data.frame(pars) %>% pmap(lotv_wrapper, currpop = currpop, days = days)


```


