---
title: "Assignment 3"
author: "Zoe Rennie"
date: "2023-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(purrr)
library(ggpubr)
```

# Sensitivity Analysis

```{r}
# source almond_yield and profit functions
source(here("R", "almond_yield.R"))
source(here("R", "compute_profit.R"))
# read in data
clim_data <- as.data.frame(read.table(here("data","clim.txt"), header=T))
#test profit function
compute_profit(almond_yield(clim_data))
#create range of variation for yield and price per ton
baseline_yield <- runif(min=.7, 
                max = 1.3, n=20)
price_per_ton <- runif(min=1800, 
                    max = 4200, n=20)
#combine parameters to a dataframe
params = cbind.data.frame(baseline_yield, price_per_ton)
#get results of sensitivity analysis
results = params %>% pmap(compute_profit, yield_anomalies=almond_yield(clim_data), acres = 100)
#add parameters from each run to profit
profit <- map_df(results,`[`, c("profit"))
profit_params <- cbind.data.frame(profit, params)
#graph results
p1 = ggplot(profit_params, aes(baseline_yield, profit, col=price_per_ton))+geom_point(cex=2)+
  labs(y="Profit ($)", x="Baseline Yield (tons/acre) \n above which total yield is more profitable") #not sure about this labeling was just replicating the example
p2 = ggplot(profit_params, aes(price_per_ton, profit, col=baseline_yield))+geom_point(cex=2)+
  labs(y="Profit ($)", x="Price per ton ($)")
ggarrange(p1,p2)
```