---
title: "Assignment 2"
author: "Kort Alexander, Zoe Rennie"
date: "2023-04-20"
output: 
  html_document:
    theme: darkly
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(dplyr.summarise.inform = FALSE)
library(here)
library(tidyverse)
library(dplyr)
library(knitr)
```

## Conceptual Model

<iframe src="https://drive.google.com/file/d/1RBin0vPf28FLi4Kk2_a_jUzPj1cneZXn/preview" width="640" height="480" allow="autoplay"></iframe>

## Climate Data Function

Below is implementation of the function almond_yield to obtain the minimum, maximum, and mean almond yield anomalies.

```{r}
# source almond_yield function
source(here("R", "almond_yield.R"))

#test function
clim_data <- as.data.frame(read.table(here("data","clim.txt"), header=T))
almond_yield(clim_data)
```

## Sensitivity Analysis

```{r}
Tmincoeff1_range <- runif(n = 10, min = -1, max = 1)

sens_results <- Tmincoeff1_range %>% map(~almond_yield(clim_data, Tmincoeff1 = .x))

Pcoeff1_range <- runif(n = 10, min = -1, max = 1)
sens_results2 <- Pcoeff1_range %>% map(~almond_yield(clim_data, Pcoeff1 = .x))

df <- as.data.frame(do.call(rbind, sens_results2))
df <- df %>% mutate(Pcoeff1 = Pcoeff1_range)

ggplot(df, aes(x = Pcoeff1, y = mean_yield_anomaly)) +
  geom_point()
```

